--- 
- 
  hosts: all
  name: "Hello World Sample"
  tasks: 
    - 
      debug: 
        msg: "Hello World!"
      name: "Hello Message"
- 
  debug: 
    msg: |-
        {{ msg.split('
        ') }}
  name: "Print some debug information"
  tags: debug_info
  vars: 
    msg: "Module Variables (\"vars\"):\n\
        --------------------------------\n\
        {{ vars | to_nice_json }} \n\n\
        Environment Variables (\"environment\"):\n\
        --------------------------------\n\
        {{ environment | to_nice_json }} \n\n\
        GROUP NAMES Variables (\"group_names\"):\n\
        --------------------------------\n\
        {{ group_names | to_nice_json }}\n\n\
        GROUPS Variables (\"groups\"):\n\
        --------------------------------\n\
        {{ groups | to_nice_json }}\n\n\
        HOST Variables (\"hostvars\"):\n\
        --------------------------------\n\
        {{ hostvars | to_nice_json }} \n"
