---
- hosts: all
  task:
    - debug:
        msg: vCenter = {{VMWARE_HOST}} vcenter user = {{VMWARE_USER}}  password ={{VMWARE_PASSWORD}} cert valid = {{VMWARE_VALIDATE_CERTS}}
    ignore_errors: true