---
- name: Testing vCenter connection and parameters
  hosts: all
  tasks:
    - name: Debuging the parameters
      debug:
        msg: vCenter = {{ lookup("env", "VMWARE_HOST") }} {{ lookup("env", "VMWARE_USER") }} {{ lookup("env", "VMWARE_PASSWORD") }}