---
- name: Testing vCenter connection and parameters
- hosts: all
  tasks:
    - name: Debuging the parameters
      debug:
        msg: vCenter = {{VMWARE_HOST}} vcenter user = {{VMWARE_USER}}  password ={{VMWARE_PASSWORD}} cert valid = {{VMWARE_VALIDATE_CERTS}}
