---
- name: Create a VM from a template
  hosts: all
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: '{{vm_name}}'
      template: '{{template_name}}'
      datacenter: '{{datacenter}}'
      folder: '{{folder}}'
      state: poweredon
      cluster: '{{cluster}}'
      networks:
      - name: 'VM Network'
        type: dhcp
      wait_for_ip_address: yes
    register: vm_output

  - debug:
      var: vm_output  

  - name: Add additional disks
    vmware_guest_disk:
      uuid: "{{ vm_output.instance.instance_uuid }}"
      use_instance_uuid: true
      datacenter: "{{ datacenter }}"
      disk: 
      - size_gb: "{{ item }}"
        type: thick
        scsi_controller: 1
        autoselect_datastore: true
        state: present
    when: item | length > 0
    loop: 
    - "{{ disk1_gb | default('') }}"
    - "{{ disk2_gb | default('') }}"
    - "{{ disk3_gb | default('') }}"